IF DB_ID(N'GaMawelaCommunityPlatform') IS NULL
BEGIN
  CREATE DATABASE [GaMawelaCommunityPlatform];
END;
GO

USE [GaMawelaCommunityPlatform];
GO

IF OBJECT_ID(N'dbo.Users', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Users (
    Id NVARCHAR(100) NOT NULL PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL,
    FullName NVARCHAR(255) NOT NULL,
    RoleName NVARCHAR(50) NOT NULL DEFAULT N'member',
    StatusName NVARCHAR(50) NOT NULL DEFAULT N'active',
    MembershipNumber NVARCHAR(50) NULL,
    PreferredLanguage NVARCHAR(10) NOT NULL DEFAULT N'en',
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );

  CREATE UNIQUE INDEX IX_Users_Email ON dbo.Users (Email);
END;
GO

IF COL_LENGTH(N'dbo.Users', N'MembershipNumber') IS NULL
BEGIN
  ALTER TABLE dbo.Users ADD MembershipNumber NVARCHAR(50) NULL;
END;
GO

IF COL_LENGTH(N'dbo.Users', N'PasswordHash') IS NULL
BEGIN
  ALTER TABLE dbo.Users ADD PasswordHash NVARCHAR(255) NULL;
END;
GO

IF OBJECT_ID(N'dbo.Mines', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Mines (
    Id NVARCHAR(100) NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Company NVARCHAR(255) NOT NULL,
    CompanyFilter NVARCHAR(100) NOT NULL,
    Commodity NVARCHAR(100) NOT NULL,
    MineType NVARCHAR(50) NOT NULL,
    Corridor NVARCHAR(50) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    CommunityImpact NVARCHAR(MAX) NOT NULL,
    SlpStatus NVARCHAR(50) NOT NULL,
    MapX DECIMAL(5,2) NOT NULL,
    MapY DECIMAL(5,2) NOT NULL
  );
END;
GO

IF OBJECT_ID(N'dbo.SlpCommitments', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.SlpCommitments (
    Id NVARCHAR(100) NOT NULL PRIMARY KEY,
    MineId NVARCHAR(100) NOT NULL,
    MineName NVARCHAR(255) NOT NULL,
    Company NVARCHAR(255) NOT NULL,
    CommitmentType NVARCHAR(100) NOT NULL,
    StatusName NVARCHAR(50) NOT NULL,
    ReportYear NVARCHAR(30) NOT NULL,
    Notes NVARCHAR(MAX) NOT NULL,
    Detail NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.TransparencySignals', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TransparencySignals (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Title NVARCHAR(255) NOT NULL,
    MetricValue INT NOT NULL,
    Summary NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.TransparencyMatrixRows', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TransparencyMatrixRows (
    Id NVARCHAR(100) NOT NULL PRIMARY KEY,
    Theme NVARCHAR(255) NOT NULL,
    OwnerName NVARCHAR(255) NOT NULL,
    DisclosureScore INT NOT NULL,
    DeliveryScore INT NOT NULL,
    YouthAccessScore INT NOT NULL,
    StatusName NVARCHAR(50) NOT NULL,
    RiskLevel NVARCHAR(50) NOT NULL,
    NoteText NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.Documents', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Documents (
    Id NVARCHAR(100) NOT NULL PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Category NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    SourceName NVARCHAR(255) NOT NULL,
    PublishedDate NVARCHAR(50) NOT NULL,
    FileUrl NVARCHAR(1000) NULL,
    ExternalUrl NVARCHAR(1000) NULL,
    FileName NVARCHAR(255) NULL,
    IsFeatured BIT NOT NULL DEFAULT 0,
    LanguageCode NVARCHAR(10) NOT NULL DEFAULT N'en',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF COL_LENGTH(N'dbo.Documents', N'ExternalUrl') IS NULL
BEGIN
  ALTER TABLE dbo.Documents ADD ExternalUrl NVARCHAR(1000) NULL;
END;
GO

IF COL_LENGTH(N'dbo.Documents', N'FileName') IS NULL
BEGIN
  ALTER TABLE dbo.Documents ADD FileName NVARCHAR(255) NULL;
END;
GO

IF COL_LENGTH(N'dbo.Documents', N'IsFeatured') IS NULL
BEGIN
  ALTER TABLE dbo.Documents ADD IsFeatured BIT NOT NULL CONSTRAINT DF_Documents_IsFeatured DEFAULT 0;
END;
GO

IF COL_LENGTH(N'dbo.Documents', N'LanguageCode') IS NULL
BEGIN
  ALTER TABLE dbo.Documents ADD LanguageCode NVARCHAR(10) NOT NULL CONSTRAINT DF_Documents_LanguageCode DEFAULT N'en';
END;
GO

IF OBJECT_ID(N'dbo.EngagementEntries', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.EngagementEntries (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    EntryKind NVARCHAR(50) NOT NULL,
    SectionName NVARCHAR(100) NOT NULL,
    FullName NVARCHAR(255) NOT NULL,
    MessageText NVARCHAR(MAX) NOT NULL,
    IssueType NVARCHAR(100) NULL,
    FileName NVARCHAR(255) NULL,
    FileUrl NVARCHAR(1000) NULL,
    PreferredLanguage NVARCHAR(10) NOT NULL DEFAULT N'en',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );

  CREATE INDEX IX_EngagementEntries_SectionName_CreatedAt
    ON dbo.EngagementEntries (SectionName, CreatedAt DESC);
END;
GO

IF COL_LENGTH(N'dbo.EngagementEntries', N'FileUrl') IS NULL
BEGIN
  ALTER TABLE dbo.EngagementEntries ADD FileUrl NVARCHAR(1000) NULL;
END;
GO

IF OBJECT_ID(N'dbo.Sources', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Sources (
    Id NVARCHAR(100) NOT NULL PRIMARY KEY,
    Title NVARCHAR(500) NOT NULL,
    Publisher NVARCHAR(255) NOT NULL,
    Category NVARCHAR(100) NOT NULL,
    SourceDate NVARCHAR(50) NOT NULL,
    Href NVARCHAR(1000) NOT NULL,
    Summary NVARCHAR(MAX) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.PlatformUpdates', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.PlatformUpdates (
    Id NVARCHAR(100) NOT NULL PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Detail NVARCHAR(MAX) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID(N'dbo.Opportunities', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Opportunities (
    Id NVARCHAR(100) NOT NULL PRIMARY KEY,
    Category NVARCHAR(100) NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    OwnerName NVARCHAR(255) NOT NULL,
    StatusName NVARCHAR(100) NOT NULL,
    Summary NVARCHAR(MAX) NOT NULL,
    HowToApply NVARCHAR(MAX) NOT NULL,
    Href NVARCHAR(500) NOT NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END;
GO
